### ISSUE TITLE
Contents of popup replace buffer contents

### ISSUE THREAD

**Issue by swflint** [A7R7/org-popup-posframe#1]
When using `org-popup-posframe`, the contents of the popup replace the buffer it is called from.

**Comment by A7R7** [comment]
I've meet this several times when I was developing this package, and I've fixed them all. 
So this could due to incompatible org mode versions. I should have made my code more robust and more compatible. 
What org version are you using anyway?

**Comment by swflint** [comment]
`1564776b8faeed162f487ed4c6f98e66fb2de34f`, i.e., the latest.  In particular, I notice it happening for `org-todo`.

**Comment by A7R7** [comment]
That makes sense. the hack for `org-todo` is a little complex, some tiny changes to the original code could break it

**Comment by swflint** [comment]
Ahh, okay.  Would you add a `Package-Requires` header for minimum versions?  And maybe a note as to which versions are known to work?

**Comment by A7R7** [comment]
Yeah! I'm already doing this, it takes time to check codes from different commits. 

Btw, I couldn't find the commit `1564776b8faeed162f487ed4c6f98e66fb2de34f`  from either https://git.savannah.gnu.org/git/emacs/org-mode.git or https://git.tecosaur.net/tec/org-mode. Maybe this commit got modified somehow.

**Comment by A7R7** [comment]
2def4a4 should fix this bug
